version: "3.8"

services:
  backend:
    build: ./projet-cloud-backend
    ports:
      - "3001:3001"
    env_file:
      - ./projet-cloud-backend/.env
    restart: always

  frontend:
    build: ./projet-cloud-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
